"""Tests for SQL generator."""

import pytest
from src.models.attribute import Attribute
from src.models.entity import Entity
from src.models.association import Association
from src.models.link import Link
from src.models.project import Project
from src.controllers.sql_generator import SQLGenerator


class TestSQLGenerator:
    """Tests for SQL generation."""

    @pytest.fixture
    def simple_project(self):
        """Create a simple project with one entity."""
        project = Project()

        # Add attributes
        project.dictionary.add_attribute(
            Attribute(name="id_client", data_type="INT", is_primary_key=True)
        )
        project.dictionary.add_attribute(
            Attribute(name="nom", data_type="VARCHAR", size=100)
        )
        project.dictionary.add_attribute(
            Attribute(name="email", data_type="VARCHAR", size=255)
        )

        # Add entity
        entity = Entity(
            name="Client",
            attributes=["id_client", "nom", "email"]
        )
        project.add_entity(entity)

        return project

    @pytest.fixture
    def n_n_relationship_project(self):
        """Create a project with N-N relationship."""
        project = Project()

        # Add attributes
        project.dictionary.add_attribute(
            Attribute(name="id_etudiant", data_type="INT", is_primary_key=True)
        )
        project.dictionary.add_attribute(
            Attribute(name="nom_etudiant", data_type="VARCHAR", size=100)
        )
        project.dictionary.add_attribute(
            Attribute(name="id_cours", data_type="INT", is_primary_key=True)
        )
        project.dictionary.add_attribute(
            Attribute(name="titre_cours", data_type="VARCHAR", size=200)
        )
        project.dictionary.add_attribute(
            Attribute(name="note", data_type="DECIMAL", size=5)
        )

        # Add entities
        etudiant = Entity(
            name="Etudiant",
            attributes=["id_etudiant", "nom_etudiant"]
        )
        project.add_entity(etudiant)

        cours = Entity(
            name="Cours",
            attributes=["id_cours", "titre_cours"]
        )
        project.add_entity(cours)

        # Add association with carrying attribute
        inscription = Association(
            name="Inscription",
            attributes=["note"]  # Carrying attribute
        )
        project.add_association(inscription)

        # Add links (both N-N)
        project.add_link(Link(
            entity_id=etudiant.id,
            association_id=inscription.id,
            cardinality_min="0",
            cardinality_max="N"
        ))
        project.add_link(Link(
            entity_id=cours.id,
            association_id=inscription.id,
            cardinality_min="0",
            cardinality_max="N"
        ))

        return project

    def test_generate_simple_table(self, simple_project):
        """Test generating a simple table."""
        generator = SQLGenerator(simple_project)
        sql = generator.generate()

        assert "CREATE TABLE client" in sql
        assert "id_client INT" in sql
        assert "nom VARCHAR(100)" in sql
        assert "email VARCHAR(255)" in sql
        assert "PRIMARY KEY (id_client)" in sql

    def test_generate_junction_table(self, n_n_relationship_project):
        """Test generating junction table for N-N relationship."""
        generator = SQLGenerator(n_n_relationship_project)
        sql = generator.generate()

        # Check entity tables
        assert "CREATE TABLE etudiant" in sql
        assert "CREATE TABLE cours" in sql

        # Check junction table
        assert "CREATE TABLE inscription" in sql
        assert "fk_etudiant_id_etudiant" in sql
        assert "fk_cours_id_cours" in sql
        assert "note DECIMAL(5)" in sql  # Carrying attribute
        assert "FOREIGN KEY" in sql

    def test_safe_name_conversion(self, simple_project):
        """Test that names are converted to safe SQL identifiers."""
        generator = SQLGenerator(simple_project)

        # Add entity with special characters
        simple_project.dictionary.add_attribute(
            Attribute(name="id_produit", data_type="INT", is_primary_key=True)
        )
        simple_project.add_entity(Entity(
            name="Produit Special",
            attributes=["id_produit"]
        ))

        sql = generator.generate()

        # Should be lowercase with underscores
        assert "produit_special" in sql

    def test_empty_project(self):
        """Test generating SQL for empty project."""
        project = Project()
        generator = SQLGenerator(project)
        sql = generator.generate()

        assert "Generated by AnalyseSI" in sql
        assert "CREATE TABLE" not in sql
